### ISSUE TITLE
Security Hole

### ISSUE THREAD

**Issue by r-j-taylor** [KeeninVye/skrraper#2]
Found a security hole in this tool, not sure if you're aware of it. Once you get this up and running with all your accounts added, somebody could find all your account credentials in the plaintext file. This is especially problematic if you use the same username and password for everything, like I do. I think you could fix this with something like a Caesar Cipher (I'm an expert if you need help), which makes it nearly impossible for people to read the text. You're welcome in advance for bringing this to your attention, just doing my duty.

**Comment by KeeninVye** [comment]
Thank you for bringing this to my attention, we will resolve the issue at an appropriate pace.

In the mean time, here are a few very basic things you can do to mitigate this risk:
1. Don’t use the same password for everything.
2. Don’t share your computer or its login information with anyone, giving them access to the configuration file.

If you are still worried about your credentials being found by someone, feel free to make a pull request.  Thank you.
